### PR TITLE
Update Memory-Addresses.txt

### PR DESCRIPTION
**Pull request by RudiAk**
Hello, followed your instructions, first time doing this i ended up with ffxiv.exe+010330F8
Hopefully it works!

### CODE REVIEW

**Comment by SG57** [comment]
It's worth a shot.  I do not have a subscription to test it myself, I ought to add the ability to test other memory addresses in to the app hmm...  Actually you should be able to test this yourself if you go to the settings file for your program.  For windows 7 it's located i think here:

C:\Users\ username \Local Settings\Application Data\FFXIV-Nexus-Progress

Open it up, replace that old value with your new one.  save it.  Open up the ffxiv nexus progress app and it will load that memory address from the file.

**Comment by SG57** [comment]
If you're free later, I wouldn't mind skyping and walk you thru the process of testing this out to see if it works first.
I might just throw a new version out that supports entering your own memory addresses in to test.

**Comment by RudiAk** [comment]
Thanks for getting back, i have actually being using an offline version since yesterday. 
- Downloaded the Zip file and opened it in Visual Studio and pointed the location to my desktop folder where the mem file was stored. it works!

Light values have changed however but the app is still good in keep track of the 0 - 2000 i guess?.

 (i cannot seem to access Local Settings on my PC though; says access denied ).

**Comment by SG57** [comment]
Ok I'll take your word for it!

What do you mean light values changed?  Does it no longer "finish" at 2000 light?

**Pull request merged**
